/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMyProfile"];
        trace?: never;
    };
    "/api/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getUserByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top posts sorted by votes */
        get: operations["PostsController_findTopPosts"];
        put?: never;
        /** Create a new post */
        post: operations["PostsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/somas/{somaId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all posts in a soma */
        get: operations["PostsController_findBySoma"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get post by ID */
        get: operations["PostsController_findOne"];
        put?: never;
        post?: never;
        /** Delete post */
        delete: operations["PostsController_remove"];
        options?: never;
        head?: never;
        /** Update post */
        patch: operations["PostsController_update"];
        trace?: never;
    };
    "/api/v1/somas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all somas */
        get: operations["SomaController_findAll"];
        put?: never;
        /** Create a new soma (community) */
        post: operations["SomaController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/somas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get soma by slug */
        get: operations["SomaController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all comments for a post (flat list, sorted by creation) */
        get: operations["CommentsController_findAll"];
        put?: never;
        /** Create a top-level comment on a post */
        post: operations["CommentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{commentId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply to an existing comment */
        post: operations["CommentsController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete comment */
        delete: operations["CommentsController_remove"];
        options?: never;
        head?: never;
        /** Update comment content */
        patch: operations["CommentsController_update"];
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all notifications for current user */
        get: operations["NotificationsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark notification as read */
        patch: operations["NotificationsController_markAsRead"];
        trace?: never;
    };
    "/api/v1/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert (Create or Update) a vote */
        post: operations["VotesController_upsert"];
        /** Delete a vote */
        delete: operations["VotesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/upload-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate presigned URL for media upload */
        post: operations["MediaController_createUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media collection for a post */
        get: operations["MediaController_getMediaByPost"];
        put?: never;
        /** Attach media to a post */
        post: operations["MediaController_attachMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give an award to a post or comment */
        post: operations["AwardsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all awards for a post */
        get: operations["AwardsController_findAllByPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{commentId}/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all awards for a comment */
        get: operations["AwardsController_findAllByComment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global feed (recent posts) */
        get: operations["FeedController_getGlobalFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/somas/{somaId}/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feed for a specific soma */
        get: operations["FeedController_getSomaFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserProfileDto: Record<string, never>;
        CreatePostDto: {
            /**
             * @description Title of the post
             * @example The Future of AI in 2025
             */
            title: string;
            /**
             * @description Body/content of the post
             * @example Here are my thoughts on AI developments...
             */
            body?: string;
            /**
             * @description UUID of the soma where the post will be created
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            somaId: string;
        };
        Post: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example The Future of AI in 2025 */
            title: string;
            /** @example Here are my thoughts on AI developments... */
            body: Record<string, never> | null;
            /** @example 123e4567-e89b-12d3-a456-426614174001 */
            authorId: string;
            /** @example 123e4567-e89b-12d3-a456-426614174002 */
            somaId: string;
            /**
             * @description Number of times the post has been viewed
             * @example 0
             */
            impressions: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdatePostDto: {
            /**
             * @description Updated title of the post
             * @example The Future of AI in 2025 - Updated
             */
            title?: string;
            /**
             * @description Updated body/content of the post
             * @example Here are my updated thoughts...
             */
            body?: string;
        };
        CreateSomaDto: {
            /**
             * @description Name of the soma
             * @example Technology News
             */
            name: string;
            /**
             * @description URL-safe slug for the soma (lowercase, alphanumeric and hyphens only)
             * @example tech-news
             */
            slug: string;
            /**
             * @description Description of the soma
             * @example A community for discussing the latest in technology
             */
            description?: string;
        };
        Soma: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example tech-news */
            slug: string;
            /** @example Technology News */
            name: string;
            /** @example A community for discussing the latest in technology */
            description: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateCommentDto: {
            /**
             * @description The content of the comment
             * @example This is a great post!
             */
            content: string;
        };
        Comment: {
            /** @description Comment UUID */
            id: string;
            /** @description Content of the comment */
            content: string;
            /** @description Author UUID */
            authorId: string;
            /** @description Post UUID */
            postId: string;
            /** @description Parent Comment UUID */
            parentCommentId: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updatedAt: string;
        };
        UpdateCommentDto: {
            /**
             * @description The content of the comment
             * @example This is a great post!
             */
            content?: string;
        };
        Notification: {
            /** @description Notification UUID */
            id: string;
            /** @description Recipient User UUID */
            userId: string;
            /** @description Notification type (e.g. COMMENT, AWARD) */
            type: string;
            /** @description Notification message */
            message: string;
            /** @description Target type (e.g. POST, COMMENT) */
            targetType: Record<string, never> | null;
            /** @description Target UUID */
            targetId: Record<string, never> | null;
            /** @description Read timestamp */
            readAt: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
        };
        CreateVoteDto: {
            /**
             * @description The type of the target being voted on
             * @example POST
             * @enum {string}
             */
            targetType: "POST" | "COMMENT";
            /**
             * @description The UUID of the target being voted on
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            targetId: string;
            /**
             * @description The value of the vote: +1 (upvote) or -1 (downvote)
             * @example 1
             * @enum {number}
             */
            value: 1 | -1;
        };
        Vote: {
            /** @description Vote UUID */
            id: string;
            /** @description User UUID who cast the vote */
            userId: string;
            /**
             * @description Target type
             * @enum {string}
             */
            targetType: "POST" | "COMMENT";
            /** @description Target UUID */
            targetId: string;
            /** @description Vote value (+1 or -1) */
            value: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
        };
        DeleteVoteDto: {
            /**
             * @description The type of the target being un-voted
             * @example POST
             * @enum {string}
             */
            targetType: "POST" | "COMMENT";
            /**
             * @description The UUID of the target being un-voted
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            targetId: string;
        };
        UploadIntentDto: {
            /**
             * @description Type of media to upload
             * @example IMAGE
             * @enum {string}
             */
            mediaType: "IMAGE" | "VIDEO" | "AUDIO";
            /**
             * @description MIME type of the file
             * @example image/jpeg
             */
            mimeType: string;
            /**
             * @description Name of the file
             * @example photo.jpg
             */
            fileName: string;
        };
        UploadIntentResponseDto: {
            /**
             * @description Presigned URL for uploading the file
             * @example https://bucket.s3.region.amazonaws.com/...
             */
            presignedUploadUrl: string;
            /**
             * @description Final public URL of the uploaded file
             * @example https://bucket.s3.region.amazonaws.com/soma/user-id/...
             */
            finalPublicUrl: string;
        };
        MediaItemDto: {
            /**
             * @description Type of media
             * @example IMAGE
             * @enum {string}
             */
            type: "IMAGE" | "VIDEO" | "AUDIO";
            /**
             * @description URL of the uploaded media
             * @example https://bucket.s3.region.amazonaws.com/soma/user-id/...
             */
            originalUrl: string;
            /**
             * @description Optional metadata for the media item
             * @example {
             *       "width": 1920,
             *       "height": 1080
             *     }
             */
            metadata?: Record<string, never>;
        };
        AttachMediaDto: {
            /** @description Array of media items to attach to the post */
            media: components["schemas"]["MediaItemDto"][];
        };
        MediaItem: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174001 */
            collectionId: string;
            /**
             * @example IMAGE
             * @enum {string}
             */
            type: "IMAGE" | "VIDEO" | "AUDIO";
            /** @example https://bucket.s3.region.amazonaws.com/soma/user-id/... */
            originalUrl: string;
            /**
             * @example {
             *       "width": 1920,
             *       "height": 1080
             *     }
             */
            metadata: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        MediaCollection: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174002 */
            postId: string;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["MediaItem"][];
        };
        CreateAwardDto: {
            /**
             * @description The type of the target being awarded
             * @example POST
             * @enum {string}
             */
            targetType: "POST" | "COMMENT";
            /**
             * @description The UUID of the target being awarded
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            targetId: string;
            /**
             * @description Name of the award
             * @example Gold
             */
            name: string;
        };
        Award: {
            /** @description Award UUID */
            id: string;
            /** @description User UUID who gave the award */
            awardedById: string;
            /**
             * @description Target type
             * @enum {string}
             */
            targetType: "POST" | "COMMENT";
            /** @description Target UUID */
            targetId: string;
            /** @description Name of the award */
            name: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
        };
        FeedUser: {
            id: string;
            username: string;
            displayName: Record<string, never> | null;
        };
        FeedSoma: {
            id: string;
            slug: string;
            name: string;
        };
        FeedMediaItem: {
            type: string;
            originalUrl: string;
        };
        FeedMediaCollection: {
            items: components["schemas"]["FeedMediaItem"][];
        };
        FeedItem: {
            id: string;
            title: string;
            body: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            author: components["schemas"]["FeedUser"];
            soma: components["schemas"]["FeedSoma"];
            media: components["schemas"]["FeedMediaCollection"] | null;
            voteCount: number;
            awardCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findTopPosts: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Number of posts per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of top posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
        };
    };
    PostsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description Post created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Invalid input or soma does not exist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Creator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findBySoma: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soma UUID */
                somaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of posts in the soma */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
        };
    };
    PostsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not post author or admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostDto"];
            };
        };
        responses: {
            /** @description Post updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not post author or admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SomaController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all somas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Soma"][];
                };
            };
        };
    };
    SomaController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSomaDto"];
            };
        };
        responses: {
            /** @description Soma created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Soma"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Soma with this slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SomaController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soma slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soma found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Soma"];
                };
            };
            /** @description Soma not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    CommentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Comment created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Invalid input or post not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Parent Comment UUID */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Reply created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Invalid input or parent comment not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not comment author or admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentDto"];
            };
        };
        responses: {
            /** @description Comment updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not comment author or admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    NotificationsController_markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VotesController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVoteDto"];
            };
        };
        responses: {
            /** @description Vote created or updated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vote"];
                };
            };
            /** @description Invalid input or target not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VotesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteVoteDto"];
            };
        };
        responses: {
            /** @description Vote deleted successfully or did not exist */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_createUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentDto"];
            };
        };
        responses: {
            /** @description Presigned upload URL generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Creator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_getMediaByPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media collection found or null if no media attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCollection"];
                };
            };
        };
    };
    MediaController_attachMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachMediaDto"];
            };
        };
        responses: {
            /** @description Media attached successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCollection"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not post author or admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AwardsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAwardDto"];
            };
        };
        responses: {
            /** @description Award created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Award"];
                };
            };
            /** @description Invalid input or target not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AwardsController_findAllByPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Post UUID */
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of awards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Award"][];
                };
            };
        };
    };
    AwardsController_findAllByComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment UUID */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of awards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Award"][];
                };
            };
        };
    };
    FeedController_getGlobalFeed: {
        parameters: {
            query?: {
                /** @description Number of posts to return (default: 20) */
                limit?: number;
                /** @description Cursor for pagination (Post ID) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recent posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItem"][];
                };
            };
        };
    };
    FeedController_getSomaFeed: {
        parameters: {
            query?: {
                /** @description Number of posts to return (default: 20) */
                limit?: number;
                /** @description Cursor for pagination (Post ID) */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Soma UUID */
                somaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recent posts in soma */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItem"][];
                };
            };
        };
    };
}
