/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query ExploreAutocomplete($input: AutocompleteInput!) {\n    autocomplete(input: $input) {\n      id\n      kind\n      title\n      subtitle\n      slug\n    }\n  }\n": typeof types.ExploreAutocompleteDocument,
    "\n  query SearchPage($input: SearchInput!) {\n    search(input: $input) {\n      totalCount\n      nodes {\n        id\n        kind\n        title\n        subtitle\n        slug\n        imageUrl\n      }\n    }\n  }\n": typeof types.SearchPageDocument,
    "\n  query MyStudioPosts {\n    myStudioPosts {\n      id\n      title\n      body\n      excerpt\n      mediaUrl\n      mediaStatus\n      visibility\n      createdAt\n      updatedAt\n      soma {\n        name\n        slug\n      }\n    }\n  }\n": typeof types.MyStudioPostsDocument,
    "\n  query GetPublicSomaSeo($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        coverUrl\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": typeof types.GetPublicSomaSeoDocument,
    "\n  query GetPublicPostSeo($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        updatedAt\n        visibility\n        soma {\n          name\n          slug\n        }\n        author {\n          profile {\n            username\n            displayName\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetPublicPostSeoDocument,
    "\n  query GetPublicProfileSeo($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": typeof types.GetPublicProfileSeoDocument,
    "\n  query GetSomaCreatorReviewQueue($somaId: String!) {\n    somaCreatorReviewQueue(somaId: $somaId) {\n      id\n      applicantId\n      disciplines\n      portfolioUrls\n      processSamples\n      statement\n      status\n      createdAt\n      moderationConsent\n    }\n  }\n": typeof types.GetSomaCreatorReviewQueueDocument,
    "\n  query GetCreatorReviewApplicant($id: String!) {\n    getUserById(id: $id) {\n      __typename\n      ... on UserResponseDto {\n        id\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n        }\n      }\n    }\n  }\n": typeof types.GetCreatorReviewApplicantDocument,
    "\n  mutation ReviewCreatorApplication(\n    $input: ReviewSomaCreatorApplicationInput!\n  ) {\n    reviewSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n        reviewedAt\n        reviewerNote\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": typeof types.ReviewCreatorApplicationDocument,
    "\n  mutation SubmitCreatorApplication($input: SubmitSomaCreatorApplicationInput!) {\n    submitSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": typeof types.SubmitCreatorApplicationDocument,
    "\n  query GetMyCreatorApplications {\n    mySomaCreatorApplications {\n      id\n      somaId\n      disciplines\n      portfolioUrls\n      statement\n      processSamples\n      status\n      createdAt\n      updatedAt\n      reviewedAt\n      reviewerNote\n    }\n    getAllSomas {\n      id\n      name\n      slug\n    }\n  }\n": typeof types.GetMyCreatorApplicationsDocument,
    "\n  mutation CreateComment($postId: String!, $data: CreateCommentDto!) {\n    createComment(postId: $postId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": typeof types.CreateCommentDocument,
    "\n  mutation ReplyToComment($commentId: String!, $data: CreateCommentDto!) {\n    replyToComment(commentId: $commentId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": typeof types.ReplyToCommentDocument,
    "\n  query GetCommentsByPost($postId: String!) {\n    getCommentsByPost(postId: $postId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": typeof types.GetCommentsByPostDocument,
    "\n  query GetCommentsByUser($userId: String!) {\n    getCommentsByUser(userId: $userId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": typeof types.GetCommentsByUserDocument,
    "\n  query GetNotifications { getNotifications { id recipientId actorId eventType eventData readAt createdAt } }\n": typeof types.GetNotificationsDocument,
    "\n  query GetNotificationActor($id: String!) {\n    getUserById(id: $id) { __typename ... on UserResponseDto { profile { displayName username } } }\n  }\n": typeof types.GetNotificationActorDocument,
    "\n  mutation MarkNotificationAsRead($id: String!) {\n    markNotificationAsRead(id: $id) {\n      __typename\n      ... on Notification { id readAt }\n      ... on NotFoundError { message }\n      ... on UnauthorizedError { message }\n    }\n  }\n": typeof types.MarkNotificationAsReadDocument,
    "\n  mutation CreateUploadIntent($data: UploadIntentDto!) {\n    createUploadIntent(data: $data) {\n      assetId\n      presignedUploadUrl\n    }\n  }\n": typeof types.CreateUploadIntentDocument,
    "\n  mutation CreatePost($data: CreatePostDto!) {\n    createPost(data: $data) {\n      __typename\n      ... on Post {\n        id\n        title\n        visibility\n        soma {\n          slug\n        }\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": typeof types.CreatePostDocument,
    "\n  query GetPostAttachments($postId: String!) {\n    getMediaByPost(postId: $postId) {\n      items {\n        originalUrl\n        type\n        metadata {\n          width\n          height\n        }\n      }\n    }\n  }\n": typeof types.GetPostAttachmentsDocument,
    "\n  query GetPostById($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        voteCount\n        userVoteValue\n        commentCount\n        soma {\n          name\n          slug\n        }\n        author {\n          emailVerified\n          profile {\n            username\n            displayName\n            avatarUrl\n            bio\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetPostByIdDocument,
    "\n  query GetGlobalFeed {\n    getGlobalFeed {\n      id\n      title\n      excerpt\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": typeof types.GetGlobalFeedDocument,
    "\n  query GetPostsByUser($userId: String!) {\n    getPostsByUser(userId: $userId) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n          bio\n        }\n      }\n    }\n  }\n": typeof types.GetPostsByUserDocument,
    "\n  query GetSomaFeed($somaId: String!, $limit: Int) {\n    getSomaFeed(somaId: $somaId, limit: $limit) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": typeof types.GetSomaFeedDocument,
    "\n  mutation UpsertVote($data: CreateVoteDto!) {\n    upsertVote(data: $data)\n  }\n": typeof types.UpsertVoteDocument,
    "\n  mutation RemoveVote($data: DeleteVoteDto!) {\n    removeVote(data: $data)\n  }\n": typeof types.RemoveVoteDocument,
    "\n  mutation CreateSoma($data: CreateSomaDto!) {\n    createSoma(data: $data) {\n      __typename\n      ... on Soma {\n        id\n        slug\n        name\n      }\n      ... on InvalidInputError {\n        message\n      }\n    }\n  }\n": typeof types.CreateSomaDocument,
    "\n  query GetSomaBySlug($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        memberCount\n        weeklyVisitorCount\n        coverUrl\n      }\n    }\n  }\n": typeof types.GetSomaBySlugDocument,
    "\n  query GetAllSomas {\n    getAllSomas {\n      id\n      name\n      slug\n      description\n      memberCount\n      weeklyVisitorCount\n      coverUrl\n    }\n  }\n": typeof types.GetAllSomasDocument,
    "\n  query MyAccountSessions {\n    mySessions {\n      id\n      clientType\n      deviceName\n      userAgent\n      createdAt\n      lastUsedAt\n      expiresAt\n    }\n  }\n": typeof types.MyAccountSessionsDocument,
    "\n  mutation RevokeAccountSession($sessionId: String!) {\n    revokeSession(sessionId: $sessionId)\n  }\n": typeof types.RevokeAccountSessionDocument,
    "\n  mutation RevokeAllAccountSessions {\n    revokeAllSessions\n  }\n": typeof types.RevokeAllAccountSessionsDocument,
    "\n  query GetFollowStatus($userId: String!) {\n    getFollowStatus(userId: $userId) {\n      __typename\n      isFollowing\n    }\n  }\n": typeof types.GetFollowStatusDocument,
    "\n  mutation Follow($userId: String!) {\n    follow(userId: $userId) {\n      __typename\n      ... on FollowResponse {\n        success\n        responseMessage: message\n      }\n      ... on InvalidInputError {\n        errorMessage: message\n      }\n      ... on NotFoundError {\n        errorMessage: message\n      }\n    }\n  }\n": typeof types.FollowDocument,
    "\n  mutation Unfollow($userId: String!) {\n    unfollow(userId: $userId) {\n      __typename\n      success\n      message\n    }\n  }\n": typeof types.UnfollowDocument,
    "\n  query GetMe {\n    me {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": typeof types.GetMeDocument,
    "\n  query GetUserByUsername($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        id\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": typeof types.GetUserByUsernameDocument,
    "\n  mutation UpdateMyProfile($data: UpdateUserProfileDto!) {\n    updateMyProfile(data: $data) {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n      ... on NotFoundError {\n        message\n      }\n    }\n  }\n": typeof types.UpdateMyProfileDocument,
    "\n  query GetFollowers($userId: String!) {\n    getFollowers(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n": typeof types.GetFollowersDocument,
    "\n  query GetFollowing($userId: String!) {\n    getFollowing(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n": typeof types.GetFollowingDocument,
};
const documents: Documents = {
    "\n  query ExploreAutocomplete($input: AutocompleteInput!) {\n    autocomplete(input: $input) {\n      id\n      kind\n      title\n      subtitle\n      slug\n    }\n  }\n": types.ExploreAutocompleteDocument,
    "\n  query SearchPage($input: SearchInput!) {\n    search(input: $input) {\n      totalCount\n      nodes {\n        id\n        kind\n        title\n        subtitle\n        slug\n        imageUrl\n      }\n    }\n  }\n": types.SearchPageDocument,
    "\n  query MyStudioPosts {\n    myStudioPosts {\n      id\n      title\n      body\n      excerpt\n      mediaUrl\n      mediaStatus\n      visibility\n      createdAt\n      updatedAt\n      soma {\n        name\n        slug\n      }\n    }\n  }\n": types.MyStudioPostsDocument,
    "\n  query GetPublicSomaSeo($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        coverUrl\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.GetPublicSomaSeoDocument,
    "\n  query GetPublicPostSeo($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        updatedAt\n        visibility\n        soma {\n          name\n          slug\n        }\n        author {\n          profile {\n            username\n            displayName\n          }\n        }\n      }\n    }\n  }\n": types.GetPublicPostSeoDocument,
    "\n  query GetPublicProfileSeo($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": types.GetPublicProfileSeoDocument,
    "\n  query GetSomaCreatorReviewQueue($somaId: String!) {\n    somaCreatorReviewQueue(somaId: $somaId) {\n      id\n      applicantId\n      disciplines\n      portfolioUrls\n      processSamples\n      statement\n      status\n      createdAt\n      moderationConsent\n    }\n  }\n": types.GetSomaCreatorReviewQueueDocument,
    "\n  query GetCreatorReviewApplicant($id: String!) {\n    getUserById(id: $id) {\n      __typename\n      ... on UserResponseDto {\n        id\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n        }\n      }\n    }\n  }\n": types.GetCreatorReviewApplicantDocument,
    "\n  mutation ReviewCreatorApplication(\n    $input: ReviewSomaCreatorApplicationInput!\n  ) {\n    reviewSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n        reviewedAt\n        reviewerNote\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": types.ReviewCreatorApplicationDocument,
    "\n  mutation SubmitCreatorApplication($input: SubmitSomaCreatorApplicationInput!) {\n    submitSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": types.SubmitCreatorApplicationDocument,
    "\n  query GetMyCreatorApplications {\n    mySomaCreatorApplications {\n      id\n      somaId\n      disciplines\n      portfolioUrls\n      statement\n      processSamples\n      status\n      createdAt\n      updatedAt\n      reviewedAt\n      reviewerNote\n    }\n    getAllSomas {\n      id\n      name\n      slug\n    }\n  }\n": types.GetMyCreatorApplicationsDocument,
    "\n  mutation CreateComment($postId: String!, $data: CreateCommentDto!) {\n    createComment(postId: $postId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": types.CreateCommentDocument,
    "\n  mutation ReplyToComment($commentId: String!, $data: CreateCommentDto!) {\n    replyToComment(commentId: $commentId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": types.ReplyToCommentDocument,
    "\n  query GetCommentsByPost($postId: String!) {\n    getCommentsByPost(postId: $postId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": types.GetCommentsByPostDocument,
    "\n  query GetCommentsByUser($userId: String!) {\n    getCommentsByUser(userId: $userId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": types.GetCommentsByUserDocument,
    "\n  query GetNotifications { getNotifications { id recipientId actorId eventType eventData readAt createdAt } }\n": types.GetNotificationsDocument,
    "\n  query GetNotificationActor($id: String!) {\n    getUserById(id: $id) { __typename ... on UserResponseDto { profile { displayName username } } }\n  }\n": types.GetNotificationActorDocument,
    "\n  mutation MarkNotificationAsRead($id: String!) {\n    markNotificationAsRead(id: $id) {\n      __typename\n      ... on Notification { id readAt }\n      ... on NotFoundError { message }\n      ... on UnauthorizedError { message }\n    }\n  }\n": types.MarkNotificationAsReadDocument,
    "\n  mutation CreateUploadIntent($data: UploadIntentDto!) {\n    createUploadIntent(data: $data) {\n      assetId\n      presignedUploadUrl\n    }\n  }\n": types.CreateUploadIntentDocument,
    "\n  mutation CreatePost($data: CreatePostDto!) {\n    createPost(data: $data) {\n      __typename\n      ... on Post {\n        id\n        title\n        visibility\n        soma {\n          slug\n        }\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n": types.CreatePostDocument,
    "\n  query GetPostAttachments($postId: String!) {\n    getMediaByPost(postId: $postId) {\n      items {\n        originalUrl\n        type\n        metadata {\n          width\n          height\n        }\n      }\n    }\n  }\n": types.GetPostAttachmentsDocument,
    "\n  query GetPostById($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        voteCount\n        userVoteValue\n        commentCount\n        soma {\n          name\n          slug\n        }\n        author {\n          emailVerified\n          profile {\n            username\n            displayName\n            avatarUrl\n            bio\n          }\n        }\n      }\n    }\n  }\n": types.GetPostByIdDocument,
    "\n  query GetGlobalFeed {\n    getGlobalFeed {\n      id\n      title\n      excerpt\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": types.GetGlobalFeedDocument,
    "\n  query GetPostsByUser($userId: String!) {\n    getPostsByUser(userId: $userId) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n          bio\n        }\n      }\n    }\n  }\n": types.GetPostsByUserDocument,
    "\n  query GetSomaFeed($somaId: String!, $limit: Int) {\n    getSomaFeed(somaId: $somaId, limit: $limit) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n": types.GetSomaFeedDocument,
    "\n  mutation UpsertVote($data: CreateVoteDto!) {\n    upsertVote(data: $data)\n  }\n": types.UpsertVoteDocument,
    "\n  mutation RemoveVote($data: DeleteVoteDto!) {\n    removeVote(data: $data)\n  }\n": types.RemoveVoteDocument,
    "\n  mutation CreateSoma($data: CreateSomaDto!) {\n    createSoma(data: $data) {\n      __typename\n      ... on Soma {\n        id\n        slug\n        name\n      }\n      ... on InvalidInputError {\n        message\n      }\n    }\n  }\n": types.CreateSomaDocument,
    "\n  query GetSomaBySlug($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        memberCount\n        weeklyVisitorCount\n        coverUrl\n      }\n    }\n  }\n": types.GetSomaBySlugDocument,
    "\n  query GetAllSomas {\n    getAllSomas {\n      id\n      name\n      slug\n      description\n      memberCount\n      weeklyVisitorCount\n      coverUrl\n    }\n  }\n": types.GetAllSomasDocument,
    "\n  query MyAccountSessions {\n    mySessions {\n      id\n      clientType\n      deviceName\n      userAgent\n      createdAt\n      lastUsedAt\n      expiresAt\n    }\n  }\n": types.MyAccountSessionsDocument,
    "\n  mutation RevokeAccountSession($sessionId: String!) {\n    revokeSession(sessionId: $sessionId)\n  }\n": types.RevokeAccountSessionDocument,
    "\n  mutation RevokeAllAccountSessions {\n    revokeAllSessions\n  }\n": types.RevokeAllAccountSessionsDocument,
    "\n  query GetFollowStatus($userId: String!) {\n    getFollowStatus(userId: $userId) {\n      __typename\n      isFollowing\n    }\n  }\n": types.GetFollowStatusDocument,
    "\n  mutation Follow($userId: String!) {\n    follow(userId: $userId) {\n      __typename\n      ... on FollowResponse {\n        success\n        responseMessage: message\n      }\n      ... on InvalidInputError {\n        errorMessage: message\n      }\n      ... on NotFoundError {\n        errorMessage: message\n      }\n    }\n  }\n": types.FollowDocument,
    "\n  mutation Unfollow($userId: String!) {\n    unfollow(userId: $userId) {\n      __typename\n      success\n      message\n    }\n  }\n": types.UnfollowDocument,
    "\n  query GetMe {\n    me {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": types.GetMeDocument,
    "\n  query GetUserByUsername($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        id\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n": types.GetUserByUsernameDocument,
    "\n  mutation UpdateMyProfile($data: UpdateUserProfileDto!) {\n    updateMyProfile(data: $data) {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n      ... on NotFoundError {\n        message\n      }\n    }\n  }\n": types.UpdateMyProfileDocument,
    "\n  query GetFollowers($userId: String!) {\n    getFollowers(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n": types.GetFollowersDocument,
    "\n  query GetFollowing($userId: String!) {\n    getFollowing(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n": types.GetFollowingDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ExploreAutocomplete($input: AutocompleteInput!) {\n    autocomplete(input: $input) {\n      id\n      kind\n      title\n      subtitle\n      slug\n    }\n  }\n"): (typeof documents)["\n  query ExploreAutocomplete($input: AutocompleteInput!) {\n    autocomplete(input: $input) {\n      id\n      kind\n      title\n      subtitle\n      slug\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchPage($input: SearchInput!) {\n    search(input: $input) {\n      totalCount\n      nodes {\n        id\n        kind\n        title\n        subtitle\n        slug\n        imageUrl\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchPage($input: SearchInput!) {\n    search(input: $input) {\n      totalCount\n      nodes {\n        id\n        kind\n        title\n        subtitle\n        slug\n        imageUrl\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MyStudioPosts {\n    myStudioPosts {\n      id\n      title\n      body\n      excerpt\n      mediaUrl\n      mediaStatus\n      visibility\n      createdAt\n      updatedAt\n      soma {\n        name\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  query MyStudioPosts {\n    myStudioPosts {\n      id\n      title\n      body\n      excerpt\n      mediaUrl\n      mediaStatus\n      visibility\n      createdAt\n      updatedAt\n      soma {\n        name\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPublicSomaSeo($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        coverUrl\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPublicSomaSeo($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        coverUrl\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPublicPostSeo($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        updatedAt\n        visibility\n        soma {\n          name\n          slug\n        }\n        author {\n          profile {\n            username\n            displayName\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPublicPostSeo($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        updatedAt\n        visibility\n        soma {\n          name\n          slug\n        }\n        author {\n          profile {\n            username\n            displayName\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPublicProfileSeo($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPublicProfileSeo($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSomaCreatorReviewQueue($somaId: String!) {\n    somaCreatorReviewQueue(somaId: $somaId) {\n      id\n      applicantId\n      disciplines\n      portfolioUrls\n      processSamples\n      statement\n      status\n      createdAt\n      moderationConsent\n    }\n  }\n"): (typeof documents)["\n  query GetSomaCreatorReviewQueue($somaId: String!) {\n    somaCreatorReviewQueue(somaId: $somaId) {\n      id\n      applicantId\n      disciplines\n      portfolioUrls\n      processSamples\n      statement\n      status\n      createdAt\n      moderationConsent\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCreatorReviewApplicant($id: String!) {\n    getUserById(id: $id) {\n      __typename\n      ... on UserResponseDto {\n        id\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCreatorReviewApplicant($id: String!) {\n    getUserById(id: $id) {\n      __typename\n      ... on UserResponseDto {\n        id\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ReviewCreatorApplication(\n    $input: ReviewSomaCreatorApplicationInput!\n  ) {\n    reviewSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n        reviewedAt\n        reviewerNote\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ReviewCreatorApplication(\n    $input: ReviewSomaCreatorApplicationInput!\n  ) {\n    reviewSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n        reviewedAt\n        reviewerNote\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SubmitCreatorApplication($input: SubmitSomaCreatorApplicationInput!) {\n    submitSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SubmitCreatorApplication($input: SubmitSomaCreatorApplicationInput!) {\n    submitSomaCreatorApplication(input: $input) {\n      __typename\n      ... on SomaCreatorApplication {\n        id\n        status\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMyCreatorApplications {\n    mySomaCreatorApplications {\n      id\n      somaId\n      disciplines\n      portfolioUrls\n      statement\n      processSamples\n      status\n      createdAt\n      updatedAt\n      reviewedAt\n      reviewerNote\n    }\n    getAllSomas {\n      id\n      name\n      slug\n    }\n  }\n"): (typeof documents)["\n  query GetMyCreatorApplications {\n    mySomaCreatorApplications {\n      id\n      somaId\n      disciplines\n      portfolioUrls\n      statement\n      processSamples\n      status\n      createdAt\n      updatedAt\n      reviewedAt\n      reviewerNote\n    }\n    getAllSomas {\n      id\n      name\n      slug\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateComment($postId: String!, $data: CreateCommentDto!) {\n    createComment(postId: $postId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateComment($postId: String!, $data: CreateCommentDto!) {\n    createComment(postId: $postId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ReplyToComment($commentId: String!, $data: CreateCommentDto!) {\n    replyToComment(commentId: $commentId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ReplyToComment($commentId: String!, $data: CreateCommentDto!) {\n    replyToComment(commentId: $commentId, data: $data) {\n      __typename\n      ... on AsyncAccepted {\n        commandId\n      }\n      ... on Comment {\n        id\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on NotFoundError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCommentsByPost($postId: String!) {\n    getCommentsByPost(postId: $postId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCommentsByPost($postId: String!) {\n    getCommentsByPost(postId: $postId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCommentsByUser($userId: String!) {\n    getCommentsByUser(userId: $userId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCommentsByUser($userId: String!) {\n    getCommentsByUser(userId: $userId) {\n      id\n      postId\n      parentCommentId\n      content\n      voteCount\n      userVoteValue\n      createdAt\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetNotifications { getNotifications { id recipientId actorId eventType eventData readAt createdAt } }\n"): (typeof documents)["\n  query GetNotifications { getNotifications { id recipientId actorId eventType eventData readAt createdAt } }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetNotificationActor($id: String!) {\n    getUserById(id: $id) { __typename ... on UserResponseDto { profile { displayName username } } }\n  }\n"): (typeof documents)["\n  query GetNotificationActor($id: String!) {\n    getUserById(id: $id) { __typename ... on UserResponseDto { profile { displayName username } } }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkNotificationAsRead($id: String!) {\n    markNotificationAsRead(id: $id) {\n      __typename\n      ... on Notification { id readAt }\n      ... on NotFoundError { message }\n      ... on UnauthorizedError { message }\n    }\n  }\n"): (typeof documents)["\n  mutation MarkNotificationAsRead($id: String!) {\n    markNotificationAsRead(id: $id) {\n      __typename\n      ... on Notification { id readAt }\n      ... on NotFoundError { message }\n      ... on UnauthorizedError { message }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateUploadIntent($data: UploadIntentDto!) {\n    createUploadIntent(data: $data) {\n      assetId\n      presignedUploadUrl\n    }\n  }\n"): (typeof documents)["\n  mutation CreateUploadIntent($data: UploadIntentDto!) {\n    createUploadIntent(data: $data) {\n      assetId\n      presignedUploadUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePost($data: CreatePostDto!) {\n    createPost(data: $data) {\n      __typename\n      ... on Post {\n        id\n        title\n        visibility\n        soma {\n          slug\n        }\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePost($data: CreatePostDto!) {\n    createPost(data: $data) {\n      __typename\n      ... on Post {\n        id\n        title\n        visibility\n        soma {\n          slug\n        }\n      }\n      ... on InvalidInputError {\n        message\n      }\n      ... on UnauthorizedError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPostAttachments($postId: String!) {\n    getMediaByPost(postId: $postId) {\n      items {\n        originalUrl\n        type\n        metadata {\n          width\n          height\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPostAttachments($postId: String!) {\n    getMediaByPost(postId: $postId) {\n      items {\n        originalUrl\n        type\n        metadata {\n          width\n          height\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPostById($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        voteCount\n        userVoteValue\n        commentCount\n        soma {\n          name\n          slug\n        }\n        author {\n          emailVerified\n          profile {\n            username\n            displayName\n            avatarUrl\n            bio\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPostById($id: String!) {\n    getPostById(id: $id) {\n      __typename\n      ... on Post {\n        id\n        title\n        excerpt\n        body\n        mediaUrl\n        createdAt\n        voteCount\n        userVoteValue\n        commentCount\n        soma {\n          name\n          slug\n        }\n        author {\n          emailVerified\n          profile {\n            username\n            displayName\n            avatarUrl\n            bio\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetGlobalFeed {\n    getGlobalFeed {\n      id\n      title\n      excerpt\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetGlobalFeed {\n    getGlobalFeed {\n      id\n      title\n      excerpt\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPostsByUser($userId: String!) {\n    getPostsByUser(userId: $userId) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n          bio\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPostsByUser($userId: String!) {\n    getPostsByUser(userId: $userId) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n          bio\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSomaFeed($somaId: String!, $limit: Int) {\n    getSomaFeed(somaId: $somaId, limit: $limit) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSomaFeed($somaId: String!, $limit: Int) {\n    getSomaFeed(somaId: $somaId, limit: $limit) {\n      id\n      title\n      excerpt\n      body\n      mediaUrl\n      media {\n        items {\n          originalUrl\n          type\n          metadata {\n            width\n            height\n          }\n        }\n      }\n      createdAt\n      voteCount\n      userVoteValue\n      commentCount\n      soma {\n        name\n        slug\n      }\n      author {\n        emailVerified\n        profile {\n          username\n          displayName\n          avatarUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpsertVote($data: CreateVoteDto!) {\n    upsertVote(data: $data)\n  }\n"): (typeof documents)["\n  mutation UpsertVote($data: CreateVoteDto!) {\n    upsertVote(data: $data)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveVote($data: DeleteVoteDto!) {\n    removeVote(data: $data)\n  }\n"): (typeof documents)["\n  mutation RemoveVote($data: DeleteVoteDto!) {\n    removeVote(data: $data)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateSoma($data: CreateSomaDto!) {\n    createSoma(data: $data) {\n      __typename\n      ... on Soma {\n        id\n        slug\n        name\n      }\n      ... on InvalidInputError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateSoma($data: CreateSomaDto!) {\n    createSoma(data: $data) {\n      __typename\n      ... on Soma {\n        id\n        slug\n        name\n      }\n      ... on InvalidInputError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSomaBySlug($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        memberCount\n        weeklyVisitorCount\n        coverUrl\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSomaBySlug($slug: String!) {\n    getSomaBySlug(slug: $slug) {\n      __typename\n      ... on Soma {\n        id\n        name\n        slug\n        description\n        memberCount\n        weeklyVisitorCount\n        coverUrl\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllSomas {\n    getAllSomas {\n      id\n      name\n      slug\n      description\n      memberCount\n      weeklyVisitorCount\n      coverUrl\n    }\n  }\n"): (typeof documents)["\n  query GetAllSomas {\n    getAllSomas {\n      id\n      name\n      slug\n      description\n      memberCount\n      weeklyVisitorCount\n      coverUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MyAccountSessions {\n    mySessions {\n      id\n      clientType\n      deviceName\n      userAgent\n      createdAt\n      lastUsedAt\n      expiresAt\n    }\n  }\n"): (typeof documents)["\n  query MyAccountSessions {\n    mySessions {\n      id\n      clientType\n      deviceName\n      userAgent\n      createdAt\n      lastUsedAt\n      expiresAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RevokeAccountSession($sessionId: String!) {\n    revokeSession(sessionId: $sessionId)\n  }\n"): (typeof documents)["\n  mutation RevokeAccountSession($sessionId: String!) {\n    revokeSession(sessionId: $sessionId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RevokeAllAccountSessions {\n    revokeAllSessions\n  }\n"): (typeof documents)["\n  mutation RevokeAllAccountSessions {\n    revokeAllSessions\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFollowStatus($userId: String!) {\n    getFollowStatus(userId: $userId) {\n      __typename\n      isFollowing\n    }\n  }\n"): (typeof documents)["\n  query GetFollowStatus($userId: String!) {\n    getFollowStatus(userId: $userId) {\n      __typename\n      isFollowing\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Follow($userId: String!) {\n    follow(userId: $userId) {\n      __typename\n      ... on FollowResponse {\n        success\n        responseMessage: message\n      }\n      ... on InvalidInputError {\n        errorMessage: message\n      }\n      ... on NotFoundError {\n        errorMessage: message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Follow($userId: String!) {\n    follow(userId: $userId) {\n      __typename\n      ... on FollowResponse {\n        success\n        responseMessage: message\n      }\n      ... on InvalidInputError {\n        errorMessage: message\n      }\n      ... on NotFoundError {\n        errorMessage: message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Unfollow($userId: String!) {\n    unfollow(userId: $userId) {\n      __typename\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation Unfollow($userId: String!) {\n    unfollow(userId: $userId) {\n      __typename\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMe {\n    me {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMe {\n    me {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUserByUsername($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        id\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUserByUsername($username: String!) {\n    userByUsername(username: $username) {\n      __typename\n      ... on UserResponseDto {\n        id\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateMyProfile($data: UpdateUserProfileDto!) {\n    updateMyProfile(data: $data) {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n      ... on NotFoundError {\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateMyProfile($data: UpdateUserProfileDto!) {\n    updateMyProfile(data: $data) {\n      __typename\n      ... on UserResponseDto {\n        id\n        email\n        platformRole\n        emailVerified\n        profile {\n          username\n          displayName\n          bio\n          avatarUrl\n          coverUrl\n        }\n      }\n      ... on NotFoundError {\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFollowers($userId: String!) {\n    getFollowers(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n"): (typeof documents)["\n  query GetFollowers($userId: String!) {\n    getFollowers(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetFollowing($userId: String!) {\n    getFollowing(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n"): (typeof documents)["\n  query GetFollowing($userId: String!) {\n    getFollowing(userId: $userId) {\n      id\n      displayName\n      username\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;