/** @format */

import type { Metadata } from "next";
import { Fraunces, Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers";
import HeaderBlock from "@/components/header-block";

const nunito = Nunito({ subsets: ["latin"], variable: "--font-sans" });

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-heading",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", nunito.variable, fraunces.variable)} suppressHydrationWarning>
      <body className="antialiased font-sans bg-background text-foreground selection:bg-accent selection:text-accent-foreground">
        <Providers>
          <HeaderBlock />
          {children}
        </Providers>
      </body>
    </html>
  );
}
